Booking:
  text_login: Login
  text_company_profile: Company Profile         
  text_profile: Personal Information           
  text_profile_name: Name       
  text_profile_phone: Phone Number        
  text_profile_mail: E-mail       
  text_profile_position: Job Position       
  text_title_booking_for_business_customer: Book Parcel Delivery - Main Branch       
  text_title_booking_for_general_customer: Book Parcel Delivery
  text_menu_booking: Book Parcel Delivery
  text_btn_add: Add
  text_btn_next: Next
  text_term_and_condition: "Terms and Conditions of SPEED-D (Speed D) Parcel Delivery Service as of " 
  text_version: " (Version 2)"
  text_title: Create Parcel       
  text_title_booking_list: Booking List 
  text_title_parcel_list: Parcel List   
  text_title_booking_summary: Booking Summary     
  text_parcel_sender_information: Sender Information  
  text_phone_sender: Phone Number * 
  text_name_sender: Name *  
  text_address_sender: Address Details *   
  text_postcode_sender: Sub-district/ District/ Province/ Postal Code *    
  text_parcel_receiver_information: Receiver Information    
  text_phone_receiver: Phone Number *   
  text_name_receiver: Name *    
  text_location_receiver: Delivery Location Information      
  text_send_home: Deliver to Home
  text_address_receiver: Address Details *     
  text_postcode_receiver: Sub-district/ District/ Province/ Postal Code *     
  text_postcode_receiver_1: Sub-district/ District/ Province/ Postal Code
  text_select_store_on_map: Select Store
  text_booking_list: Booking List     
  text_edit_booking_list: Edit Booking List
  text_parcel_type: Parcel Type
  text_booking_name: Booking Name
  text_search_store_on_map: Search Store 7-eleven
  text_save: Save
  text_draft_status: Draft     
  text_draft_save: Save Draft
  text_booking_id_label: 'Booking ID:'
  text_booking_time_label: 'Transaction Date & Time:'
  text_booking_name_label: 'Booking Name:'
  text_next: 'Next'
  text_parcel_booking: Book Parcel Number
  text_business_customer_parcel_id_4_start_unit: SPBD
  text_general_customer_parcel_id_4_start_unit: SPBC
  img_is_favorite:
    img_sender_heart:  Red Heart Icon
    img_receiver_heart:  Red Heart Icon
  img_not_favorite:
    img_sender_heart:  No Color Heart Icon
    img_receiver_heart:  No Color Heart Icon
  text_sender:  'Sender:'
  text_receiver:  'Receiver:'
  text_selected_coupon_and_code:  Selected Coupons and Discount Codes
  text_my_coupon_and_code:  My Coupons and Discount Codes
  text_shipping_origin_aria:  Select Shipping Origin Area
  text_parcel_status_select_shipping_origin: Select Shipping Origin 
  text_parcel_status_waiting_entering: Waiting for Parcel Entry into System
  general_parcel:
    parcel_A4: A4
    parcel_detail_A4: A4 Envelope - Measured size (width + length + height) not exceeding 51 cm.
    parcel_A3: A3
    parcel_detail_A3: A3 Envelope - Measured size (width + length + height) not exceeding 72 cm.
    parcel_XS: XS
    parcel_detail_XS: XS Box (Extra Small) - Measured size (width + length + height) not exceeding 40 cm.
    parcel_S: S
    parcel_detail_S: S Box (Small) - Measured size (width + length + height) not exceeding 60 cm.
    parcel_M: M
    parcel_detail_M: M Box (Medium) - Measured size (width + length + height) not exceeding 90 cm.
    parcel_L: L
    parcel_detail_L: L Box (Large) - Measured size (width + length + height) not exceeding 120 cm.
    parcel_XL: XL
    parcel_detail_XL: XL Box (Extra Large) - Measured size (width + length + height) not exceeding 150 cm.
    parcel_XXL: XXL
    parcel_detail_XXL: XXL Box (Super Large) - Measured size (width + length + height) not exceeding 200 cm.
  parcel_detail_insure_amount: Insurance Amount
  parcel_detail_cod: Cash on Delivery (COD)
  parcel_detail_remark: Remark
  text_print_parcel_label: Print Parcel Label
  text_paper_size:
    paper_size: Paper Size
    paper: Paper
    size_a4:  A4 Paper
    size_a5:  A5 Paper
    size_8cm:  8 cm Width Paper
  text_blank:
    origin_shipping: ''
    text_business_customer_parcel_id_4_start_unit: '-'
    text_general_customer_parcel_id_4_start_unit: '-'
    receiver_name: '-'
    receiver_phone: '-'
    receiver_address: '-'
    receiver_postcode_5_digits: '-'
    receiver_postcode_full: '-'
    parcel_size: '-'
    price_value: '-'
    buy_insurance: '-'
    cod_value: '-'
    parcel_detail_remark: '-'
    store_code: '-'
  text_default:
    discount_amount: '0'
    discount_value: '0.00'
    insurance_fee_amount: '0'
    insurance_fee_value: '0.00'
    cod_fee_amount: '0'
    cod_fee_value: '0.00'
    total_price_amount: 0
    total_price_value: '0.00'
    booking_price:  0.00 THB
  label:
    parcel_cod:  Non COD
    parcel_insure:  No Insurance
    text_postcode: Destination Postal Code
    text_store_code: Store Code
