Booking:
  text_login: เข้าสู่ระบบ
  text_company_profile: โปรไฟล์บริษัท         
  text_profile: ข้อมูลส่วนตัว           
  text_profile_name: ชื่อ       
  text_profile_phone: เบอร์โทรศัพท์        
  text_profile_mail: E-mail       
  text_profile_position: ตำแหน่งงาน       
  text_title_booking_for_business_customer: จองการจัดส่งพัสดุ สาขาหลัก       
  text_title_booking_for_general_customer: จองการจัดส่งพัสดุ
  text_menu_booking: จองการจัดส่งพัสดุ
  text_btn_add: เพิ่ม
  text_btn_next: ถัดไป
  text_term_and_condition: "ข้อกำหนดและเงื่อนไขการใช้บริการขนส่งพัสดุ SPEED-D (สปีด ดี) ณ วันที่ " 
  text_version: " (Version 2)"
  text_title: สร้างพัสดุ       
  text_title_booking_list: รายการบุ๊คกิ้ง 
  text_title_parcel_list: รายการพัสดุ   
  text_title_booking_summary: สรุปรายการบุ๊คกิ้ง     
  text_parcel_sender_information: ข้อมูลผู้ส่งพัสดุ  
  text_phone_sender: เบอร์โทรศัพท์ * 
  text_name_sender: ชื่อ *  
  text_address_sender: รายละเอียดที่อยู่ *   
  text_postcode_sender: แขวงตำบล/ อำเภอ/ จังหวัด/ รหัสไปรษณีย์ *    
  text_parcel_receiver_information: ข้อมูลผู้รับพัสดุ    
  text_phone_receiver: เบอร์โทรศัพท์ *   
  text_name_receiver: ชื่อ *    
  text_location_receiver: ข้อมูลสถานที่รับพัสดุ      
  text_send_home: ส่งที่บ้าน
  text_address_receiver: รายละเอียดที่อยู่ *     
  text_postcode_receiver: แขวงตำบล/ อำเภอ/ จังหวัด/ รหัสไปรษณีย์ *     
  text_postcode_receiver_1: แขวงตำบล/ อำเภอ/ จังหวัด/ รหัสไปรษณีย์
  text_select_store_on_map: เลือกร้าน
  text_booking_list: รายการบุ๊คกิ้ง     
  text_edit_booking_list: แก้ไขรายการบุ๊คกิ้ง
  text_parcel_type: ประเภทพัสดุ
  text_booking_name: ชื่อบุ๊คกิ้ง
  text_search_store_on_map: ค้นหาร้าน 7-eleven
  text_save: บันทึก
  text_draft_status: ร่าง     
  text_draft_save: บันทึกร่าง
  text_booking_id_label: 'บุ๊คกิ้ง ID :'
  text_booking_time_label: 'วันเวลาทำรายการ :'
  text_shipping_origin:  'ต้นทางจัดส่ง :'
  text_booking_name_label: 'ชื่อบุ๊คกิ้ง :'
  text_btn_import:  Import File
  text_btn_template:  Template
  text_next: 'ถัดไป'
  text_parcel_booking: จองเลขพัสดุ
  text_edit_complete: แก้ไขสำเร็จ
  text_business_customer_parcel_id_4_start_unit: SPBD
  text_general_customer_parcel_id_4_start_unit: SPBC
  img_is_favorite:
    img_sender_heart:  รูปหัวใจสีแดง
    img_receiver_heart:  รูปหัวใจสีแดง
  img_not_favorite:
    img_sender_heart:  รูปหัวใจไม่มีสี
    img_receiver_heart:  รูปหัวใจไม่มีสี
  text_sender:  'ผู้ส่ง :'
  text_receiver:  'ผู้รับ :'
  text_selected_coupon_and_code:  คูปองและโค้ดส่วนลดที่เลือก
  text_my_coupon_and_code:  คูปองและโค้ดส่วนลดของฉัน
  text_use_coupon:  ใช้คูปอง
  text_shipping_origin_aria:  เลือกพื้นที่ต้นทางการจัดส่ง
  text_parcel_status_select_shipping_origin: เลือกต้นทางจัดส่ง 
  text_parcel_status_waiting_entering: รอส่งพัสดุเข้าระบบ
  tab_shipping_origin:
    favorite:  เลือกรายการโปรด
    store:  เลือกร้าน 7-11 ต้นทาง
    car_pickup:  รอบรถเข้ารับพัสดุ
  pickup_schedule:
    special_car_pickup:  รอบรถพิเศษ
    general_car_pickup:  รอบรถปกติ
    pickup_date: 'วันที่รถเข้ารับพัสดุ :'
    parcel_number:  'จำนวนพัสดุ :'
    cut_off_time:  'เวลา Cut Off รอบรถ :'
    price:  'ราคา :'
    default:
      parcel_number:  '0 รายการ'
      cut_off_time:  '11:15:00'
      price:  '0 บาท'
  general_parcel:
    parcel_A4: A4
    parcel_detail_A4: A4 ซอง A4 ขนาดวัดตามสายวัด กว้าง + ยาว + สูง ไม่เกิน 51 ชม.
    parcel_A3: A3
    parcel_detail_A3: A3 ซอง A3 ขนาดวัดตามสายวัด กว้าง + ยาว + สูง ไม่เกิน 72 ชม.
    parcel_XS: XS
    parcel_detail_XS: XS กล่อง XS (เล็กพิเศษ) ขนาดวัดตามสายวัด กว้าง + ยาว + สูง ไม่เกิน 40 ชม.
    parcel_S: S
    parcel_detail_S: S กล่อง S (เล็ก) ขนาดวัดตามสายวัด กว้าง + ยาว + สูง ไม่เกิน 60 ชม.
    parcel_M: M
    parcel_detail_M: M กล่อง M (กลาง) ขนาดวัดตามสายวัด กว้าง + ยาว + สูง ไม่เกิน 90 ชม.
    parcel_L: L
    parcel_detail_L: L กล่อง L (ใหญ่) ขนาดวัดตามสายวัด กว้าง + ยาว + สูง ไม่เกิน 120 ชม.
    parcel_XL: XL
    parcel_detail_XL: XL กล่อง XL (ใหญ่มาก) ขนาดวัดตามสายวัด กว้าง + ยาว + สูง ไม่เกิน 150 ชม.
    parcel_XXL: XXL
    parcel_detail_XXL: XXL กล่อง XXL (ใหญ่พิเศษ) ขนาดวัดตามสายวัด กว้าง + ยาว + สูง ไม่เกิน 200 ชม.
  parcel_detail_insure_amount: จำนวนเงินซื้อประกัน
  parcel_detail_cod: เก็บเงินปลายทาง
  parcel_detail_remark: หมายเหตุ
  text_print_parcel_label: พิมพ์ใบจ่ายหน้าพัสดุ
  text_paper_size:
    paper_size: ขนาดกระดาษ
    paper: กระดาษ
    size_a4:  กระดาษ A4
    size_a5:  กระดาษ A5
    size_8cm:  กระดาษ หน้ากว้าง 8 ซม.
  text_blank:
    origin_shipping: ''
    text_business_customer_parcel_id_4_start_unit: '-'
    text_general_customer_parcel_id_4_start_unit: '-'
    receiver_name: '-'
    receiver_phone: '-'
    receiver_address: '-'
    receiver_postcode_5_digits: '-'
    receiver_postcode_full: '-'
    parcel_size: '-'
    price_value: '-'
    buy_insurance: '-'
    cod_value: '-'
    parcel_detail_remark: '-'
    store_code: '-'
  text_default:
    discount_amount: '0'
    discount_value: '0.00'
    insurance_fee_amount: '0'
    insurance_fee_value: '0.00'
    cod_fee_amount: '0'
    cod_fee_value: '0.00'
    total_price_amount: 0
    total_price_value: '0.00'
    booking_price:  0.00บาท
  label:
    parcel_cod:  Non COD
    parcel_insure:  ไม่มีการซื้อประกัน
    text_postcode: รหัสไปรษณีย์ปลายทาง
    text_store_code: รหัสร้าน

call_car_pick_up:
  text_call_car_pick_up:  เรียกรถเข้ารับพัสดุ สาขาหลัก
  text_parcel_pickup_schedule:  รอบรถเข้ารับพัสดุ
  text_car_round_name:  ชื่อรอบรถ
  text_parcel_type:  ประเภทพัสดุ
  text_parcel_pickup_date:  วันที่รถเข้ารับพัสดุ
  text_parcel_pickup_time:  เวลารถเข้ารับพัสดุ
  text_cut_off_time:  เวลา Cut Off รอบรถ
  text_parcel_number:  จำนวนพัสดุ
  button_save:  บันทึก
  button_cancel:  ยกเลิก
  car_round_name:
    special:  รอบพิเศษ
  parcel_type:
    dry:  พัสดุทั่วไป (Dry)
    chilled:  พัสดุควบคุมอุณหภูมิ
  parcel_pickup_time:
    morning:  ช่วงเช้า 09:00 - 12:00
    afternoon:  ช่วงบ่าย 13:00 - 16:00
  parcel_pickup_time_schedule:
    morning:  09:00:00 - 12:00 น.
  cut_off_time:  '15:00:00'
  default:
    parcel_number: 0 รายการ

dc_operaion:
  role:
    dev:  Role Dev
    admin:  แอดมินคลัง
    toei:  toei test
  title:
    homepage:  ภาพรวมงานประจำวัน
    Scan:  Scan
    Pouch:  รายการ Pouch
    Report:  รายการพัสดุแจ้งปัญหา
    Check_Notification:  ตรวจสอบแจ้งเตือน
    Waiting_Destroy:  พัสดุรอทำลาย
    Upload_Route:  อัปโหลด Route
    Check_Receiving_Cycle:  ตรวจสอบรอบการเข้ารับพัสดุ
    History_Parcel:  รายการประวัติพัสดุทั้งหมด
  dps_menu:
    Home_Page:  homepage
    Scan:  scan
    Pouch:  pouch
    Report:  reportpage
    Check_Notification:  check-notifications
    Waiting_Destroy:  waiting-destroy
    Upload_Route:  upload-route
    Check_Receiving_Cycle:  check-receiving-cycle
    History_Parcel:  historyparcel
  Check_Receiving_Cycle_Tab:
    all_parcels_received:  รายการเข้ารับพัสดุทั้งหมด
    waiting_inventory_confirm_list:  รายการรอคลังยืนยัน
  text_save_success:  บันทึกข้อมูลเรียบร้อย
  button_export:  Export File
  button_approve: approve
  parcel_pickup_details:  รายละเอียดรอบเข้ารับพัสดุ
  vehicle_type:  ประเภทที่ใช้